### ISSUE TITLE
Boot ist buggy

### ISSUE THREAD

**Issue by ghost** [HGLabor/Bingo#6]
Mehrere Leute haben schon davon berichtet, dass wenn man im F5 in das Boot geht, wird man für "Flying is not enabled on this Server" gekickt. Ich konnte gerade gar nicht in das Boot einsteigen, man würde sofort unter das Boot gebuggt. Egal von welchem Winkel immer buggte man weg. Da überall Wasser auf der Map war, war das keine schöne Situation.

**Comment by mooziii** [comment]
liegt zwar nicht am plugin aber kann flying trotzdem disablen
