### ISSUE TITLE
Man kann die Karte mit einem Trick aus der Off-Hand nehmen

### ISSUE THREAD

**Issue by SEEG2** [HGLabor/Bingo#7]
Wenn man bei Bingo die **Karte** in der **Off-Hand** hat und dann **f auf ein anderes Item drückt**, lässt sich die Karte mit diesem Item **tauschen** und man kann die Karte daraufhin nur noch verschieben wenn sie in der Hotbar ist. 
Sollte die Karte nicht mehr in der Hotbar sein, dann lässt sie sich überhaupt **nicht mehr verschieben**.

Link zum Youtube Video::
https://youtu.be/3_29_wgiEvM

**Comment by jarekaha** [comment]
Einfach nicht machen, und Fertig.

**Comment by SEEG2** [comment]
> Einfach nicht machen, und Fertig.
Was ist wenn jmd. z.B. Fackeln mit f in die Off-Hand nehmen will und dann das passiert ?

**Comment by mooziii** [comment]
es gibt immernoch /bingo
